
project:
  type: book

book:
  title:
    Shirley Cheung
  navbar: 
    logo: port_figures/3.jpg
    collapse: true
    collapse-below: lg
    background: "#FFFFFF"
    style: "docked"
    search: true
    right:
      - icon: Home
        href: "index.qmd"
      - icon: Biography
        href: "biography.qmd"
      - icon: Contact
        href: "contact.qmd"
      - icon: instagram  # Add Instagram icon
        href: "https://www.instagram.com/cheunghoiiiyi?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw=="
      - icon: facebook   # Add Facebook icon
        href: "https://www.facebook.com/shirley.cheung.98892"
      - icon: whatsapp
        href: "https://wa.me/+85266893127"
    pinned: true
    align: center
  sidebar: false
  chapters:
    - index.qmd
    - biography.qmd
    - contact.qmd

reader-mode: true

bibliography: references.bib

format:
  html:
    theme: [Lux]
    css: styles.css
    toc: false
    title-block-banner: "port_figures/banner.JPG"
    title-block-style: default
    title-block-categories: false
    title-block-banner-color: "body"

