
project:
  type: book

book:
  title:
    Shirley Cheung
    Flute · Piccolo 
  navbar: 
    logo: port_figures/3.jpg
    collapse: true
    collapse-below: lg
    background: "#FFFFFF"
    style: "docked"
    search: true
    right:
      - icon: github
    pinned: true
    align: center
  sidebar:
    title: "Profile"
    style: docked
    reader-mode: true
  repo-url: https://github.com/Sophialyc/Portfolio_final-.git
  chapters:
    - index.qmd
    - biography.qmd
    - contact.qmd

reader-mode: true

bibliography: references.bib

format:
  html:
    theme:
      light: [Lux, default]
      dark: [morph,darkly, dark.css]
    css: styles.css
    toc: false
    title-block-banner: "port_figures/banner.JPG"
    title-block-style: default
    title-block-categories: false
    title-block-banner-color: "body"

